# Generated by Django 2.1.5 on 2019-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190912_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
