# Generated by Django 2.1.5 on 2019-09-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
