# Generated by Django 2.1.5 on 2019-09-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='email1',
        ),
        migrations.AddField(
            model_name='client',
            name='email0',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email3',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email4',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email5',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email6',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email7',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email8',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email9',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
